FROM ubuntu:16.10

RUN apt-get update && \
    apt-get -y install python3-pip git && \
    pip3 install --upgrade pip

WORKDIR /src/

ADD requirements.txt /src/
RUN pip3 install -r requirements.txt

ADD requirements.build.txt /src/
RUN pip3 install -r requirements.build.txt

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

COPY . /src/
RUN make build && cp dist/cogctl /usr/bin