FROM operable/alpine-base:0.3

# Need MUSL for pyinstaller on Alpine
RUN apk -U add \
    musl=1.1.14-r14 \
    python3=3.5.2-r2 && \
    pip3 install --upgrade pip

WORKDIR /src

COPY requirements.txt /src/
RUN pip3 install -r requirements.txt

COPY . /src/
