FROM operable/elixir:1.3.1-r2

COPY mix.exs mix.lock /code/
WORKDIR /code
RUN mix deps.get
RUN MIX_ENV=test mix deps.compile
RUN MIX_ENV=prod mix deps.compile # For shortening escript build
COPY config config
COPY lib lib
RUN MIX_ENV=test mix compile # Multiple pipeline steps will need this

COPY . /code
