#!/bin/sh

export DATABASE_URL=$DATABASE_URL.$BUILDKITE_BUILD_NUMBER

cd ..

if [ ! -d cog ]; then
  echo "Setting up cog..."

  git clone git@github.com:operable/cog.git
  cd cog
else
  echo "Making sure cog is up-to-date..."

  cd cog
  git pull origin master
fi

mix do deps.get, ecto.create, ecto.migrate

echo "Starting cog..."

elixir \
--detached \
-e "File.write!(\"pid.$BUILDKITE_BUILD_NUMBER\", System.get_pid)" \
-S mix phoenix.server

while ! nc -z localhost 4000; do
  sleep 0.1
done

cd ../cogctl
