#!/bin/bash
#
# Lovingly stolen from docker-compose.
#
# Write the current commit sha to the file GITSHA. This file is included in
# packaging so that `cogctl version` can include the git sha.
#
set -e
git rev-parse --short HEAD > cogctl/GITSHA
