#!/bin/bash
#
# Lovingly stolen from docker-compose.
#
# Write the current commit sha to the file GITSHA. This file is included in
# packaging so that `cogctl version` can include the git sha.
#
set -e
git rev-parse --short HEAD > cogctl/GITSHA


# Lovingly stolen from go-relay (sort of).
#
# Writes the current tag to the file GITTAG. If the current commit
# isn't tagged then the current branch name is used.

# git describe --tags appends SHA info to
# prior tag. This subcommand detects when that happens.
tag=`git describe --tags`
dash_count=`git describe --tags | grep -o - | wc -l | sed "s/ //g"`

if [ "$dash_count" != "0" ]; then
  tag=$(git rev-parse --abbrev-ref HEAD)
fi

echo $tag > cogctl/GITTAG
